name: Build and Save Wheels (DIRECT DOWNLOAD)

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - build  # Prevent workflow from running when pushing to the build branch

permissions:
  contents: write  # Allows the workflow to push changes to the repository

jobs:
  build_wheels:
    name: Build Wheels for ${{ matrix.os }} on Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12']
        architecture: ['x64']

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies for Linux/Mac
        if: matrix.os != 'windows-latest'
        run: |
          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
            sudo apt-get update
            sudo apt-get install -y tk-dev tcl-dev libx11-dev
          elif [[ ${{ matrix.os }} == 'macos-latest' ]]; then
            brew install xquartz  # Install XQuartz to get X11 libraries
            export LIBRARY_PATH="/opt/X11/lib"  # Ensure X11 libraries are correctly linked
          fi
          python -m pip install --upgrade pip setuptools wheel

      - name: Install MSYS2 and Tcl/Tk for Windows
        if: matrix.os == 'windows-latest'
        run: |
          # Install MSYS2
          choco install msys2
          
          # Add MSYS2 to the PATH
          echo "C:/msys64/usr/bin" >> $GITHUB_PATH
          echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH

          # Update MSYS2 and install necessary packages
          C:/msys64/usr/bin/bash -lc "pacman -Syu --noconfirm"
          C:/msys64/usr/bin/bash -lc "pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-pip mingw-w64-x86_64-tcl mingw-w64-x86_64-tk"

      - name: Build Python Package in MSYS2
        if: matrix.os == 'windows-latest'
        run: |
          # Use a simpler method to convert the workspace path to MSYS2-compatible format
          GITHUB_WORKSPACE_MSYS="/c$(echo $GITHUB_WORKSPACE | cut -c 3-)"

          # Run the build in the MinGW64 shell
          C:/msys64/usr/bin/bash -lc "
          export PATH=/mingw64/bin:$PATH;
          export CC=gcc;
          export CXX=g++;
          export LDSHARED='\$CC -shared';
          export AR=ar;
          export RANLIB=ranlib;

          # Navigate to the correct workspace directory in MSYS2 format
          cd $GITHUB_WORKSPACE_MSYS;

          # Ensure we have the latest pip and build tools
          python3 -m pip install --upgrade pip setuptools wheel;

          # Build the project and create the wheel
          python3 setup.py build;
          python3 setup.py bdist_wheel;
          "

      - name: Move Windows build artifacts to dist
        if: matrix.os == 'windows-latest'
        run: |
          # Move the generated wheels to the dist/ directory in the GitHub workspace
          C:/msys64/usr/bin/bash -lc "
          GITHUB_WORKSPACE_MSYS='/c$(echo $GITHUB_WORKSPACE | cut -c 3- | sed 's/\\\\/\\//g')'
          mv $GITHUB_WORKSPACE_MSYS/dist/*.whl ./dist/"

      - name: Build wheel
        if: matrix.os != 'windows-latest'
        run: |
          python setup.py build
          python setup.py bdist_wheel  # Build the wheel
        shell: bash

      - name: Commit and push the built wheels
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git clean -fd  # Remove untracked files (such as wheel files in 'dist/')
          git checkout master
          git pull origin master  # Pull the latest changes from master
          python setup.py bdist_wheel  # Generate the wheel files
          git add .  # Add all changes to the commit
          git commit -a -m "Update wheel files for Python 3.12 on ${{ matrix.os }} (x64)"
          git push --force origin master  # Force push to overwrite the existing master branch

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}