name: Build and Save Wheels

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build Wheels for ${{ matrix.os }} on Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: '3.12'
        architecture: x64
        check-latest: true

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
        retry:
        max-attempts: 3

      # Install Tcl/Tk and build dependencies for Linux and macOS
      - name: Install dependencies for Linux/Mac
        if: matrix.os != 'windows-latest'
        run: |
          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
            sudo apt-get update
            sudo apt-get install -y tk-dev tcl-dev
          fi
          python -m pip install --upgrade pip setuptools wheel

      # Install Tcl/Tk and build dependencies for Windows
      - name: Install dependencies for Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install tcl-tk
          python -m pip install --upgrade pip setuptools wheel

      # Compile the C extension for the appropriate OS and architecture
      - name: Build wheel
        run: |
          python setup.py bdist_wheel

      # Add, commit, and push built wheel to the repository
      - name: Commit and push built wheel
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b build-artifacts  # Create a branch for artifacts if necessary
          git add dist/*                  # Assuming the wheels are stored in the 'dist/' directory
          git commit -m "Add built wheels for ${{ matrix.python-version }} on ${{ matrix.os }} (${{ matrix.architecture }})"
          git push origin build-artifacts  # Push to a specific branch, or use 'main' if desired
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate the push
