name: Build and Save Wheels

on:
  workflow_dispatch:

permissions:
  contents: write   # Allows the workflow to push changes to the repository

jobs:
  build_wheels:
    name: Build Wheels for ${{ matrix.os }} on Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12']
        architecture: ['x64']

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies for Linux/Mac
        if: matrix.os != 'windows-latest'
        run: |
          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
            sudo apt-get update
            sudo apt-get install -y tk-dev tcl-dev
          fi
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies for Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install tcl-tk
          python -m pip install --upgrade pip setuptools wheel

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Commit and push built wheel
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          rm -rf dist/*  # Discard untracked files in the 'dist/' directory
          
          # Ensure we are on the master branch and up to date
          git checkout master  # Switch to the master branch
          git pull origin master --rebase  # Pull the latest changes from the master branch

          # Rebuild the wheel file
          python setup.py bdist_wheel  # Generate the wheel files
          
          # Add the new wheel files to Git
          git add dist/*
          git commit -m "Add built wheels for ${{ matrix.python-version }} on ${{ matrix.os }} (x64)"
          
          # Push the changes to the master branch
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}