name: Build and Save Wheels

on:
  workflow_dispatch:

permissions:
  contents: write   # Allows the workflow to push changes to the repository

jobs:
  build_wheels:
    name: Build Wheels for ${{ matrix.os }} on Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12']
        architecture: ['x64']

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies for Linux/Mac
        if: matrix.os != 'windows-latest'
        run: |
          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
            sudo apt-get update
            sudo apt-get install -y tk-dev tcl-dev
          fi
          python -m pip install --upgrade pip setuptools wheel

      - name: Install dependencies for Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install tcl-tk
          python -m pip install --upgrade pip setuptools wheel

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: Commit and push built wheel
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b build-artifacts || git checkout build-artifacts  # Create or switch to branch
          git pull origin build-artifacts --rebase # Pull the latest changes from the remote branch
          git add dist/*
          git commit -m "Add built wheels for ${{ matrix.python-version }} on ${{ matrix.os }} (x64)"
          git push origin build-artifacts  # Push to the remote branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
